### ISSUE TITLE
Error connection to node

### ISSUE THREAD

**Issue by dawz0r** [svk31/bitshares-report#1]
internet@internet:~/program/bitshares-report-master$ sudo node app.js [MyUsername]
ws://127.0.0.1:8090 Failed to initialize with error connect ECONNREFUSED 127.0.0.1:8090
Error connection to node: ErrorEvent {
  target: 
   WebSocket {
     domain: null,
     _events: 
      { open: [Object],
        error: [Object],
        message: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     _error: null,
     url: 'ws://127.0.0.1:8090',
     _req: null },
  type: 'error',
  message: 'connect ECONNREFUSED 127.0.0.1:8090',
  error: 
   { Error: connect ECONNREFUSED 127.0.0.1:8090
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 8090 } }

node -v
v8.11.3

**Comment by svk31** [comment]
You need to have a witness_node API running locally at 127.0.0.1:8090

**Comment by svk31** [comment]
The library now uses elastic search by default so no need to configure your own node anymore
